SELECT ADDDATE('2024-07-02', INTERVAL 15 DAY);
SELECT SUBDATE('2024-07-02', INTERVAL 15 DAY);
SELECT NOW(), CURDATE(), CURRENT_TIME();
SELECT MONTH(NOW()), DAY(NOW()), WEEK(NOW()), HOUR(NOW()), QUARTER(NOW());

